spring.application.name=api_sistema_gestao_colaborativos
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.springframework.security=TRACE
spring.web.error.include-stacktrace=never
spring.web.error.include-message=always


